# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717101eb842e009bbb49d369ed7b1ac3350e38ec0548d052926438d200e950814a1a591a75c198c474be9ab58ec03df220a876cae3da69b43c3223a202e84a96

test:
  secret_key_base: a0695aff1669f8cf598cf6e5832f2c906f3a2b25a3a6b0c888d904e47bdd96325e4faaac562d55b95028c4082e8909cf13a8c92d4b953d98f10fcade8baa7f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
